name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 794314734433.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push vote
        run: |
          docker build -t $ECR_REGISTRY/voting-app-vote:${{ github.sha }} ./vote
          docker push $ECR_REGISTRY/voting-app-vote:${{ github.sha }}

      - name: Build and push result
        run: |
          docker build -t $ECR_REGISTRY/voting-app-result:${{ github.sha }} ./result
          docker push $ECR_REGISTRY/voting-app-result:${{ github.sha }}

      - name: Build and push worker
        run: |
          docker build -t $ECR_REGISTRY/voting-app-worker:${{ github.sha }} ./worker
          docker push $ECR_REGISTRY/voting-app-worker:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export AWS_REGION=us-east-1
            export ECR_REGISTRY=794314734433.dkr.ecr.us-east-1.amazonaws.com
            export IMAGE_TAG=${{ github.sha }}

            aws ecr get-login-password --region $AWS_REGION | \
              docker login --username AWS \
              --password-stdin $ECR_REGISTRY

            cd ~/example-voting-app

            docker compose pull
            docker compose up -d
